name: freedomflow
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

assets:
  img/logoFF02.png

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  device_preview: ^1.2.0
  get_it: ^8.0.3
  fl_chart: ^0.63.0
  get: ^4.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
